---
- name: "[{{ name }}] Creating Secrets"
  block:
   - name: "[{{ name }}] Creating Secrets"
     include_tasks: "secret-create.yml"
  tags: "{{ name }}"  
  rescue:
    - name: "[{{ name }}] Displaying Services"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "[{{ name }}] Creating Secrets"
      include_tasks: "secret-create.yml"